name: Teste

on:
  workflow_dispatch:

jobs:
  teste-badge:
    name: 'Teste Criação de Badges'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout - ${{ github.ref }}
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Generate Badge - Com
        uses: ./
        with:
          environment: env-com-token
          version: ${{ github.run_number }}
          token: ${{ secrets.SECRET_TOKEN }}

      - name: Generate Badge - Com repetido
        uses: ./
        with:
          environment: env-com-token-rep
          version: 20
          token: ${{ secrets.SECRET_TOKEN }}

      # - name: Generate Badge - Sem
      #   uses: ifGarcia/action-badge@main
      #   with:
      #     environment: env-sem-token
      #     version: ${{ github.run_number }}
