name: Teste

on:
  workflow_dispatch:

jobs:
  teste-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Badge - Com
        uses: ./action.yaml
        with:
          environment: env-com-token
          version: ${{ github.run_number }}
          token: ${{ secrets.SECRET_TOKEN }}

      - name: Generate Badge - Com repetido
        uses: ./action.yaml
        with:
          environment: env-com-token-rep
          version: 20
          token: ${{ secrets.SECRET_TOKEN }}

      # - name: Generate Badge - Sem
      #   uses: ifGarcia/action-badge@main
      #   with:
      #     environment: env-sem-token
      #     version: ${{ github.run_number }}
